name: Run Tests

on:
  workflow_dispatch:
    inputs:
      testRunType:
        description: 'Type of tests to run'
        required: true
        default: 'scenarios'
      reportsDir:
        description: 'Directory to save reports'
        required: true
        default: 'reports'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run tests using Python wrapper
        run: |
          python3 simple-calc-test-runner.py --run ${{ github.event.inputs.testRunType }} --reports-dir ${{ github.event.inputs.reportsDir }}
